worker_processes 1;

events {
	worker_connections 1024;
}

http {
	include       /etc/nginx/mime.types;
	types { text/javascript vue; }
	default_type  application/octet-stream;
	client_max_body_size 32M;
	sendfile off;

	gzip on;
	gzip_vary on;
	gzip_comp_level 6;
	gzip_min_length 1000;
	gzip_types text/plain text/css text/xml application/json application/javascript application/xml+rss image/svg+xml;

	server {
		listen 80;
		server_name localhost;

		root /usr/share/nginx/html;
		index index.html;

		location = /favicon.ico {
			root /app/root;
			try_files /favicon.ico @default_favicon;
		}

		location @default_favicon {
			root /usr/share/nginx/html;
			try_files /favicon.ico =404;
		}

		location / {
			root /usr/share/nginx/html;
			try_files $uri $uri/ /index.html;
			add_header Cache-Control "no-store";
		}

		location ~ ^/api/(ronly/|navigation/active\.vue|admin/users) {
			rewrite ^/api(/.*)$ $1 break;
			proxy_pass http://backend:8080;
			proxy_no_cache 1;
			proxy_cache_bypass 1;
			proxy_set_header Host $host;
			proxy_set_header Origin $http_origin;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		location /api/ {
			if ($request_method = GET) {
				rewrite ^/api(.*)$ /files$1 last;
			}
			rewrite ^/api(/.*)$ $1 break;
			proxy_pass http://backend:8080;
			proxy_no_cache 1;
			proxy_cache_bypass 1;
			proxy_set_header Host $host;
			proxy_set_header Origin $http_origin;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		location /files/images/ {
			internal;
			alias /app/root/images/;
			autoindex on;
			add_header Cache-Control "no-store";
		}

		location /files/ {
			internal;
			alias /app/root/;
			autoindex on;
			add_header Cache-Control "no-store";
		}
	}
}
